name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      #with:
        # Build directory where build files will be generated
        #build-dir: # default is ${{ runner.workspace }}/build
        # CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)
        #build-type: # default is Release
        # C Compiler for toolchain
        #cc: # optional
        # C++ Compiler for toolchain
        #cxx: # optional
        # CMake build target
        #target: # optional
        # Number of concurrent jobs for build and test
        #parallel: # optional, default is 4
        # Run CTest or not
        #run-test: # optional, default is false
        # Run 'cmake --install' or not
        #install-build: # optional, default is false
        # Update git submodules
        #submodule-update: # optional, default is false
        # Misc Options to pass to CMake while configuring project
        #configure-options: # optional
        # Misc Options to pass to CMake while building project using cmake --build
        #build-options: # optional
        # Misc Options to pass to CMake while installing project using cmake --install
        #install-options: # optional
        # Misc Options to pass to CTest
        #ctest-options: # optional
